export enum OrderStatusTracking {
  WAITING = "WAITING",
  CANCELED = "CANCELED",
  PRODUCT_DELIVERED_TO_CARRIER = "PRODUCT_DELIVERED_TO_CARRIER",
  PRODUCT_DELIVERED_TO_CLIENT = "PRODUCT_DELIVERED_TO_CLIENT",
}
