name: Run Unit Tests

on: [pull_request, push]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - run: |
          npm ci
          npm run build
          npm run test:unit
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
          COOKIE_PRIVATE_KEY: ${{ secrets.COOKIE_PRIVATE_KEY }}
          DOMAIN_COOKIE_TOKEN: ${{ secrets.DOMAIN_COOKIE_TOKEN }}
          SHOPPING_STORE_URL_WEB: ${{ secrets.SHOPPING_STORE_URL_WEB }}
          CONFIRM_EMAIL_PAGE_STORE_URL_WEB: ${{ secrets.CONFIRM_EMAIL_PAGE_STORE_URL_WEB }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET_ID: ${{ secrets.GOOGLE_CLIENT_SECRET_ID }}
          GOOGLE_CLIENT_REDIRECT_URL: ${{ secrets.GOOGLE_CLIENT_REDIRECT_URL }}
          NODE_MAILER_EMAIL: ${{ secrets.NODE_MAILER_EMAIL }}
          NODE_MAILER_PASS: ${{ secrets.NODE_MAILER_PASS }}
          STRIPE_PUBLIC_KEY: ${{ secrets.STRIPE_PUBLIC_KEY }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_WEBHOOK_SECRET_KEY: ${{ secrets.STRIPE_WEBHOOK_SECRET_KEY }}
          STRIPE_SUCCESS_URL: ${{ secrets.STRIPE_SUCCESS_URL }}
          STRIPE_CANCEL_URL: ${{ secrets.STRIPE_CANCEL_URL }}
          UPSTASH_REDIS_PASSWORD: ${{ secrets.UPSTASH_REDIS_PASSWORD }}
          UPSTASH_REDIS_URL: ${{ secrets.UPSTASH_REDIS_URL }}
          RUST_BACKTRACE: 1
